-- Drop booking_details table and dependent FKs if they exist to match schema.png
DROP TABLE IF EXISTS public.e_tickets CASCADE;
DROP TABLE IF EXISTS public.booking_details CASCADE;

-- Add status & banner columns to events
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS status character varying(50) DEFAULT 'ACTIVE';
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS banner_url text;

-- Add registration_start & registration_end & seat_layout to event_schedules to match schema.png
ALTER TABLE public.event_schedules ADD COLUMN IF NOT EXISTS registration_start timestamp without time zone;
ALTER TABLE public.event_schedules ADD COLUMN IF NOT EXISTS registration_end timestamp without time zone;
ALTER TABLE public.event_schedules ADD COLUMN IF NOT EXISTS seat_layout text;

-- Create e_tickets exactly matching schema.png + seat extensions (row_label & col_number)
CREATE TABLE public.e_tickets (
    ticket_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ticket_config_id integer NOT NULL,
    event_day_id integer NOT NULL,
    booking_id integer,
    ticket_code character varying,
    ticket_status character varying DEFAULT 'Available' NOT NULL, -- 'Available', 'Holding', 'Valid', 'Used', 'Canceled', 'Reserved'
    row_label character varying,
    col_number integer,
    CONSTRAINT e_tickets_pkey PRIMARY KEY (ticket_id),
    CONSTRAINT e_tickets_ticket_config_id_fkey FOREIGN KEY (ticket_config_id) REFERENCES public.ticket_configs(config_id) ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT e_tickets_event_day_id_fkey FOREIGN KEY (event_day_id) REFERENCES public.event_days(event_day_id) ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT e_tickets_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id) ON DELETE SET NULL DEFERRABLE
);

